// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "github.com/agungdwiprasetyo/agungdpcms/src/resume/domain"
import mock "github.com/stretchr/testify/mock"

import shared "github.com/agungdwiprasetyo/agungdpcms/shared"

// Experience is an autogenerated mock type for the Experience type
type Experience struct {
	mock.Mock
}

// FindByResumeID provides a mock function with given fields: resumeID
func (_m *Experience) FindByResumeID(resumeID int) <-chan []*domain.Experience {
	ret := _m.Called(resumeID)

	var r0 <-chan []*domain.Experience
	if rf, ok := ret.Get(0).(func(int) <-chan []*domain.Experience); ok {
		r0 = rf(resumeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []*domain.Experience)
		}
	}

	return r0
}

// Remove provides a mock function with given fields: data
func (_m *Experience) Remove(data *domain.Experience) shared.Result {
	ret := _m.Called(data)

	var r0 shared.Result
	if rf, ok := ret.Get(0).(func(*domain.Experience) shared.Result); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(shared.Result)
	}

	return r0
}

// Save provides a mock function with given fields: data
func (_m *Experience) Save(data *domain.Experience) shared.Result {
	ret := _m.Called(data)

	var r0 shared.Result
	if rf, ok := ret.Get(0).(func(*domain.Experience) shared.Result); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(shared.Result)
	}

	return r0
}
