// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import utils "github.com/agungdwiprasetyo/go-utils"

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: input
func (_m *Validator) Validate(input interface{}) *utils.MultiError {
	ret := _m.Called(input)

	var r0 *utils.MultiError
	if rf, ok := ret.Get(0).(func(interface{}) *utils.MultiError); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.MultiError)
		}
	}

	return r0
}
