// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resume.proto

package resume

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Filter struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=Sort,proto3" json:"Sort,omitempty"`
	SortBy               string   `protobuf:"bytes,4,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_resume_0bf0c6821ae327d7, []int{0}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Filter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Filter) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *Filter) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

type Resume struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Profile              *Profile `protobuf:"bytes,4,opt,name=Profile,proto3" json:"Profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resume) Reset()         { *m = Resume{} }
func (m *Resume) String() string { return proto.CompactTextString(m) }
func (*Resume) ProtoMessage()    {}
func (*Resume) Descriptor() ([]byte, []int) {
	return fileDescriptor_resume_0bf0c6821ae327d7, []int{1}
}
func (m *Resume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resume.Unmarshal(m, b)
}
func (m *Resume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resume.Marshal(b, m, deterministic)
}
func (dst *Resume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resume.Merge(dst, src)
}
func (m *Resume) XXX_Size() int {
	return xxx_messageInfo_Resume.Size(m)
}
func (m *Resume) XXX_DiscardUnknown() {
	xxx_messageInfo_Resume.DiscardUnknown(m)
}

var xxx_messageInfo_Resume proto.InternalMessageInfo

func (m *Resume) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Resume) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Resume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resume) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type Profile struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ResumeID             int32    `protobuf:"varint,2,opt,name=ResumeID,proto3" json:"ResumeID,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Religion             string   `protobuf:"bytes,4,opt,name=Religion,proto3" json:"Religion,omitempty"`
	Hobby                string   `protobuf:"bytes,5,opt,name=Hobby,proto3" json:"Hobby,omitempty"`
	Github               string   `protobuf:"bytes,6,opt,name=Github,proto3" json:"Github,omitempty"`
	Linkedin             string   `protobuf:"bytes,7,opt,name=Linkedin,proto3" json:"Linkedin,omitempty"`
	Instagram            string   `protobuf:"bytes,8,opt,name=Instagram,proto3" json:"Instagram,omitempty"`
	Facebook             string   `protobuf:"bytes,9,opt,name=Facebook,proto3" json:"Facebook,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_resume_0bf0c6821ae327d7, []int{2}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Profile) GetResumeID() int32 {
	if m != nil {
		return m.ResumeID
	}
	return 0
}

func (m *Profile) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Profile) GetReligion() string {
	if m != nil {
		return m.Religion
	}
	return ""
}

func (m *Profile) GetHobby() string {
	if m != nil {
		return m.Hobby
	}
	return ""
}

func (m *Profile) GetGithub() string {
	if m != nil {
		return m.Github
	}
	return ""
}

func (m *Profile) GetLinkedin() string {
	if m != nil {
		return m.Linkedin
	}
	return ""
}

func (m *Profile) GetInstagram() string {
	if m != nil {
		return m.Instagram
	}
	return ""
}

func (m *Profile) GetFacebook() string {
	if m != nil {
		return m.Facebook
	}
	return ""
}

func init() {
	proto.RegisterType((*Filter)(nil), "resume.Filter")
	proto.RegisterType((*Resume)(nil), "resume.Resume")
	proto.RegisterType((*Profile)(nil), "resume.Profile")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResumeHandlerClient is the client API for ResumeHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResumeHandlerClient interface {
	GetAllResume(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Resume, error)
}

type resumeHandlerClient struct {
	cc *grpc.ClientConn
}

func NewResumeHandlerClient(cc *grpc.ClientConn) ResumeHandlerClient {
	return &resumeHandlerClient{cc}
}

func (c *resumeHandlerClient) GetAllResume(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Resume, error) {
	out := new(Resume)
	err := c.cc.Invoke(ctx, "/resume.ResumeHandler/GetAllResume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeHandlerServer is the server API for ResumeHandler service.
type ResumeHandlerServer interface {
	GetAllResume(context.Context, *Filter) (*Resume, error)
}

func RegisterResumeHandlerServer(s *grpc.Server, srv ResumeHandlerServer) {
	s.RegisterService(&_ResumeHandler_serviceDesc, srv)
}

func _ResumeHandler_GetAllResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeHandlerServer).GetAllResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resume.ResumeHandler/GetAllResume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeHandlerServer).GetAllResume(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResumeHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resume.ResumeHandler",
	HandlerType: (*ResumeHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllResume",
			Handler:    _ResumeHandler_GetAllResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resume.proto",
}

func init() { proto.RegisterFile("resume.proto", fileDescriptor_resume_0bf0c6821ae327d7) }

var fileDescriptor_resume_0bf0c6821ae327d7 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0xe9, 0xfe, 0x5b, 0xb6, 0x9e, 0xff, 0x54, 0x08, 0x22, 0x61, 0x78, 0x31, 0x7a, 0x35,
	0x6f, 0x7a, 0x31, 0x1f, 0x40, 0x94, 0xb2, 0xad, 0x30, 0x64, 0xd4, 0x7b, 0x21, 0x75, 0xb1, 0x86,
	0xa6, 0x8d, 0x64, 0xe9, 0xc5, 0x1e, 0xdb, 0x37, 0x90, 0x9c, 0xa4, 0x55, 0xf0, 0xaa, 0xf9, 0x9d,
	0x2f, 0xfd, 0xce, 0x39, 0x5f, 0x0b, 0x73, 0x23, 0x4e, 0x5d, 0x23, 0xd2, 0x4f, 0xa3, 0xad, 0xa6,
	0xc4, 0x53, 0xf2, 0x0a, 0x64, 0x23, 0x95, 0x15, 0x86, 0x52, 0x18, 0x1f, 0x78, 0x25, 0x58, 0xb4,
	0x8c, 0x56, 0x93, 0x02, 0xcf, 0xf4, 0x1a, 0x26, 0x7b, 0xd9, 0x48, 0xcb, 0x46, 0x58, 0xf4, 0xe0,
	0x6e, 0xbe, 0x68, 0x63, 0xd9, 0xbf, 0x65, 0xb4, 0x8a, 0x0b, 0x3c, 0xd3, 0x1b, 0x20, 0xee, 0xf9,
	0x74, 0x66, 0x63, 0xac, 0x06, 0x4a, 0x6a, 0x20, 0x05, 0x76, 0xa2, 0x97, 0x30, 0xca, 0xb3, 0xe0,
	0x3e, 0xca, 0x33, 0x74, 0x51, 0x5d, 0x85, 0xd6, 0xce, 0x45, 0x75, 0x95, 0xab, 0x3d, 0xf3, 0x46,
	0xf4, 0xce, 0xee, 0x4c, 0xef, 0x60, 0x7a, 0x30, 0xfa, 0x5d, 0x2a, 0x81, 0xd6, 0xff, 0xd7, 0x57,
	0x69, 0xd8, 0x24, 0x94, 0x8b, 0x5e, 0x4f, 0xbe, 0xa2, 0xe1, 0xee, 0x9f, 0x76, 0x0b, 0x98, 0xf9,
	0x41, 0xf2, 0x2c, 0x6c, 0x33, 0xb0, 0xd3, 0x36, 0x9d, 0x52, 0xbf, 0x5a, 0x0f, 0xec, 0xdf, 0x53,
	0xb2, 0x92, 0xba, 0x0d, 0xab, 0x0d, 0xec, 0xe2, 0xd9, 0xe9, 0xb2, 0x3c, 0xb3, 0x09, 0x0a, 0x1e,
	0x5c, 0x14, 0x5b, 0x69, 0x3f, 0xba, 0x92, 0x11, 0x1f, 0x85, 0x27, 0xe7, 0xb4, 0x97, 0x6d, 0x2d,
	0x8e, 0xb2, 0x65, 0x53, 0xef, 0xd4, 0x33, 0xbd, 0x85, 0x38, 0x6f, 0x4f, 0x96, 0x57, 0x86, 0x37,
	0x6c, 0x86, 0xe2, 0x4f, 0x01, 0xe7, 0xe3, 0x6f, 0xa2, 0xd4, 0xba, 0x66, 0x71, 0x98, 0x2f, 0xf0,
	0xfa, 0x01, 0x2e, 0xfc, 0x1e, 0x3b, 0xde, 0x1e, 0x95, 0x30, 0x34, 0x85, 0xf9, 0x56, 0xd8, 0x47,
	0xa5, 0xfa, 0xdc, 0xfb, 0xb8, 0xfc, 0x77, 0x5e, 0x0c, 0xec, 0xf5, 0x92, 0xe0, 0x0f, 0x71, 0xff,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xf2, 0x7c, 0x01, 0x20, 0x02, 0x00, 0x00,
}
